mortar:
  name: "subworkshop"
  server:
    grpc:
      port: 5480
    rest:
      external:
        port: 5481
      internal:
        port: 5482
  logger:
    level: debug
    console: true
  monitor:
    address: "address:port"
    prefix: "awesome.project"
    tags:
      tag1: value
      tag2: value
      tag3: value
  middleware:
    rest:
      client:
        trace:
          request: true
          response: true
    grpc:
      server:
        log:
          request: true
          response: false
          level: debug
        trace:
          request: true
          response: true
        headers:
          - authorization
      client:
        trace:
          request: true
          response: true
    logger:
      headers:
        - x-forwarded-for
        - special-header
  handlers:
    self:
      obfuscate:
        - "pass"
        - "auth"
        - "secret"
        - "login"
        - "user"
        - "logname"
        - "token"

custom:
  authentication: "1234567890"
  token: "very secret token"
  plain: "text"
  secretmap:
    one: 1
    two: 2

jaeger:
  address: "localhost:6831"
  sampler_type: "const"
  sampler_param: 1
